version: "3"

services:
  web:
    build: .
    ports:
      - 8088:80
    volumes:
      - ./www/:/var/www/html
      - ./incl/:/var/www/incl
    networks:
      - internal_network

networks:
  internal_network: